namespace TiYf.Engine.Host;

public readonly record struct EngineMetricsSnapshot(
    double HeartbeatAgeSeconds,
    double BarLagMilliseconds,
    int PendingOrders,
    int OpenPositions,
    int ActiveOrders,
    long RiskEventsTotal,
    long AlertsTotal,
    IReadOnlyDictionary<string, long> AlertsByCategory,
    long OrderRejectsTotal,
    int StreamConnected,
    double StreamHeartbeatAgeSeconds,
    double LoopUptimeSeconds,
    long LoopIterationsTotal,
    long DecisionsTotal,
    double LoopLastSuccessUnixSeconds,
    long RiskBlocksTotal,
    long RiskThrottlesTotal,
    IReadOnlyDictionary<string, long> RiskBlocksByGate,
    IReadOnlyDictionary<string, long> RiskThrottlesByGate,
    long RiskBrokerCapBlocksTotal,
    IReadOnlyDictionary<string, long> RiskBrokerCapBlocksByGate,
    decimal? RiskBrokerDailyLossCapCcy,
    decimal RiskBrokerDailyLossUsedCcy,
    long RiskBrokerDailyLossViolationsTotal,
    long? RiskMaxPositionUnitsLimit,
    long RiskMaxPositionUnitsUsed,
    long RiskMaxPositionViolationsTotal,
    IReadOnlyDictionary<string, long> RiskSymbolCapUsage,
    IReadOnlyDictionary<string, long>? RiskSymbolCapLimits,
    IReadOnlyDictionary<string, long> RiskSymbolCapViolations,
    bool RiskCooldownEnabled,
    bool RiskCooldownActive,
    double? RiskCooldownActiveUntilUnixSeconds,
    long RiskCooldownTriggersTotal,
    int? RiskCooldownConsecutiveLosses,
    int? RiskCooldownMinutes,
    IReadOnlyDictionary<string, long> LastOrderSizeBySymbol,
    IReadOnlyDictionary<string, long> IdempotencyCacheSizes,
    long IdempotencyEvictionsTotal,
    string SlippageModel,
    double? SlippageLastPriceDelta,
    long SlippageAdjustedOrdersTotal,
    double? NewsLastEventUnixSeconds,
    long NewsEventsFetchedTotal,
    int NewsBlackoutWindowsActive,
    string NewsSourceType,
    double? GvrsRaw,
    double? GvrsEwma,
    string? GvrsBucket,
    long GvrsGateBlocksTotal,
    double? GvrsGateLastBlockUnixSeconds,
    bool GvrsGateEnabled,
    bool GvrsGateBlockingEnabled,
    bool GvrsGateWouldBlock,
    string ConfigId,
    string ConfigHash,
    string RiskConfigHash,
    string PromotionConfigHash,
    PromotionTelemetrySnapshot? PromotionTelemetry,
    int PromotionShadowPromotionsTotal,
    int PromotionShadowDemotionsTotal,
    int PromotionShadowTradesTotal,
    decimal PromotionShadowWinRatio,
    int PromotionShadowProbationDays,
    int PromotionShadowMinTrades,
    decimal PromotionShadowPromotionThreshold,
    decimal PromotionShadowDemotionThreshold,
    long ReconciliationRunsTotal,
    double? ReconciliationLastDurationSeconds,
    long ReconciliationMismatchesTotal,
    double? ReconciliationLastUnixSeconds,
    string? ReconciliationLastStatus,
    int IdempotencyPersistedLoaded,
    int IdempotencyPersistedExpired,
    double? IdempotencyPersistenceLastLoadUnix,
    IReadOnlyDictionary<string, IReadOnlyCollection<string>> SecretProvenance);
