namespace TiYf.Engine.Host;

public readonly record struct EngineMetricsSnapshot(
    double HeartbeatAgeSeconds,
    double BarLagMilliseconds,
    int PendingOrders,
    int OpenPositions,
    int ActiveOrders,
    long RiskEventsTotal,
    long AlertsTotal,
    long OrderRejectsTotal,
    int StreamConnected,
    double StreamHeartbeatAgeSeconds,
    double LoopUptimeSeconds,
    long LoopIterationsTotal,
    long DecisionsTotal,
    double LoopLastSuccessUnixSeconds,
    long RiskBlocksTotal,
    long RiskThrottlesTotal,
    IReadOnlyDictionary<string, long> RiskBlocksByGate,
    IReadOnlyDictionary<string, long> RiskThrottlesByGate,
    IReadOnlyDictionary<string, long> LastOrderSizeBySymbol,
    IReadOnlyDictionary<string, long> IdempotencyCacheSizes,
    long IdempotencyEvictionsTotal,
    string SlippageModel,
    double? SlippageLastPriceDelta,
    long SlippageAdjustedOrdersTotal,
    double? NewsLastEventUnixSeconds,
    long NewsEventsFetchedTotal,
    int NewsBlackoutWindowsActive,
    string NewsSourceType,
    double? GvrsRaw,
    double? GvrsEwma,
    string? GvrsBucket,
    long GvrsGateBlocksTotal,
    double? GvrsGateLastBlockUnixSeconds,
    bool GvrsGateEnabled,
    bool GvrsGateBlockingEnabled,
    bool GvrsGateWouldBlock,
    string ConfigHash,
    string RiskConfigHash,
    string PromotionConfigHash,
    PromotionTelemetrySnapshot? PromotionTelemetry,
    long ReconciliationMismatchesTotal,
    double? ReconciliationLastUnixSeconds,
    string? ReconciliationLastStatus,
    int IdempotencyPersistedLoaded,
    int IdempotencyPersistedExpired,
    double? IdempotencyPersistenceLastLoadUnix,
    IReadOnlyDictionary<string, IReadOnlyCollection<string>> SecretProvenance);
