# actionlint: allow-secrets ADMIN_TOKEN
name: admin-branch-protection

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Why the protection update is requested
        required: false
        default: manual
  push:
    branches:
      - main
    paths:
      - .github/workflows/admin-branch-protection.yml

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Configure branch protection on main
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          set -euo pipefail
          if [ -z "${ADMIN_TOKEN:-}" ]; then
            echo "ADMIN_TOKEN secret is not configured" >&2
            exit 1
          fi

          API="https://api.github.com/repos/${OWNER}/${REPO}/branches/main/protection"

          cat <<'JSON' > body.json
{
  "required_status_checks": {
    "strict": true,
    "checks": [
      { "context": "lint" },
      { "context": "m0-determinism" },
      { "context": "verify-strict" },
      { "context": "dataqa-tolerance" },
      { "context": "nightly-canary" }
    ]
  },
  "enforce_admins": true,
  "required_pull_request_reviews": {
    "dismissal_restrictions": {},
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": false,
    "required_approving_review_count": 1,
    "require_last_push_approval": false,
    "bypass_pull_request_allowances": {}
  },
  "restrictions": null,
  "required_linear_history": false,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "block_creations": false,
  "required_conversation_resolution": false,
  "lock_branch": false,
  "allow_fork_syncing": true
}
JSON

          curl -sS -X PUT "$API" \
            -H "Authorization: Bearer ${ADMIN_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d @body.json > response.json

          if jq -e '.message' response.json >/dev/null; then
            echo "GitHub API response:" >&2
            cat response.json >&2
            exit 1
          fi

          echo "Branch protection updated successfully."
