# actionlint: allow-secrets ADMIN_TOKEN
name: admin-branch-protection

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Why the protection update is requested
        required: false
        default: manual
  push:
    branches:
      - main
    paths:
      - .github/workflows/admin-branch-protection.yml

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Configure branch protection on main
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            if (!github.token) {
              core.setFailed('ADMIN_TOKEN secret is not configured');
              return;
            }

            const { owner, repo } = context.repo;

            const payload = {
              required_status_checks: {
                strict: true,
                checks: [
                  { context: 'lint' },
                  { context: 'm0-determinism' },
                  { context: 'verify-strict' },
                  { context: 'dataqa-tolerance' },
                  { context: 'nightly-canary' },
                ],
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                required_approving_review_count: 1,
                require_last_push_approval: false,
                bypass_pull_request_allowances: {},
              },
              restrictions: null,
              required_linear_history: false,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: false,
              lock_branch: false,
              allow_fork_syncing: true,
            };

            await github.request('PUT /repos/{owner}/{repo}/branches/{branch}/protection', {
              owner,
              repo,
              branch: 'main',
              ...payload,
            });

            core.info('Branch protection updated successfully.');