name: admin-merge
on:
  workflow_dispatch:
    inputs:
      pr:
        description: PR number
        required: true
permissions:
  pull-requests: write
  contents: write
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const prNumber = Number.parseInt('${{ inputs.pr }}', 10);
            if (!Number.isInteger(prNumber)) {
              core.setFailed('Invalid pull request number');
              return;
            }
            const result = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash',
            });
            if (!result.data.merged) {
              core.setFailed(`Merge API call returned merged=${result.data.merged}`);
              return;
            }
            core.info(`PR #${prNumber} merged as ${result.data.sha}`);
