name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -warnaserror
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Generate Journal (Sim)
        run: dotnet run --project src/TiYf.Engine.Sim -- --config sample-config.json --out journals/CI
      - name: Verify Journal
        run: dotnet run --project src/TiYf.Engine.Tools -- verify --file journals/CI/events.csv
