name: demo-daily-ctrader

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:
    inputs:
      useHostedFallback:
        description: 'Use hosted fallback runner if self-hosted is unavailable'
        required: false
        default: false
        type: boolean
      dryRun:
        description: 'Dry run mode (skip live trading)'
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  demo-daily-ctrader:
    runs-on: ${{ inputs.useHostedFallback == 'true' && 'windows-latest' || fromJson('["self-hosted","Windows","X64","tiyf-demo-live"]') }}
    timeout-minutes: 30
    defaults:
      run:
        shell: powershell
    environment: ctrader-demo
    env:
      RUN_ID: DEMO-CTRADER-DAILY-${{ github.run_number }}
      DRY_RUN: ${{ inputs.dryRun }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Relax PowerShell execution policy
        shell: cmd
        run: powershell -NonInteractive -ExecutionPolicy Bypass -Command "Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force"

      - name: Configure .NET install directory
        shell: cmd
        run: |
          set "INSTALL_DIR=%RUNNER_TEMP%\dotnet"
          if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"
          echo DOTNET_INSTALL_DIR=%INSTALL_DIR%>> "%GITHUB_ENV%"

      - name: Setup .NET 8
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: '8.0.x'

      - name: Preflight Values Checklist
        run: |
          $ErrorActionPreference = 'Stop'
          $summary = @()
          $summary += "| Check | Status |"
          $summary += "|-------|--------|"
          # CT_APP_ID
          if ($env:CT_APP_ID) {
            echo "App ID present"
            $summary += "| App ID | ✅ |"
          } else {
            $summary += "| App ID | ❌ |"
            throw "Preflight failed: CT_APP_ID missing"
          }
          # CT_APP_SECRET
          if ($env:CT_APP_SECRET) {
            echo "Client secret present"
            $summary += "| Client secret | ✅ |"
          } else {
            $summary += "| Client secret | ❌ |"
            throw "Preflight failed: CT_APP_SECRET missing"
          }
          # CT_DEMO_OAUTH_TOKEN
          if ($env:CT_DEMO_OAUTH_TOKEN) {
            echo "Access token present"
            $summary += "| Access token | ✅ |"
          } else {
            $summary += "| Access token | ❌ |"
            throw "Preflight failed: CT_DEMO_OAUTH_TOKEN missing"
          }
          # CT_DEMO_REFRESH_TOKEN
          if ($env:CT_DEMO_REFRESH_TOKEN) {
            echo "Refresh token present"
            $summary += "| Refresh token | ✅ |"
          } else {
            $summary += "| Refresh token | ❌ |"
            throw "Preflight failed: CT_DEMO_REFRESH_TOKEN missing"
          }
          # CT_DEMO_ACCOUNT_ID
          if ($env:CT_DEMO_ACCOUNT_ID) {
            $numeric = $env:CT_DEMO_ACCOUNT_ID -match '^\d+$'
            echo "Account ID present; numeric=$($numeric ? 'YES' : 'NO')"
            if ($numeric) {
              $summary += "| Account ID | ✅ |"
            } else {
              $summary += "| Account ID | ❌ |"
              throw "Preflight failed: CT_DEMO_ACCOUNT_ID not numeric"
            }
          } else {
            echo "Account ID present; numeric=NO"
            $summary += "| Account ID | ❌ |"
            throw "Preflight failed: CT_DEMO_ACCOUNT_ID missing"
          }
          # CT_DEMO_BROKER
          if ($env:CT_DEMO_BROKER) {
            $firstTwo = $env:CT_DEMO_BROKER.Substring(0, [Math]::Min(2, $env:CT_DEMO_BROKER.Length))
            echo "broker=${firstTwo}… (present)"
            $summary += "| Broker | ✅ |"
          } else {
            echo "broker= (missing)"
            $summary += "| Broker | ❌ |"
            throw "Preflight failed: CT_DEMO_BROKER missing"
          }
          echo "Environment = demo"
          $summary += "| Environment | demo |"
          # Dry run check
          if ($env:DRY_RUN -eq 'false') {
            echo "live trading disabled in this build"
            exit 0
          }
          # Write summary
          $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
          # Write artifact
          $summary | Out-File -FilePath 'preflight.sanity.txt' -Encoding utf8

      - name: Restore and build Release
        run: |
          $ErrorActionPreference = 'Stop'
          dotnet restore TiYf.Engine.sln
          dotnet build TiYf.Engine.sln -c Release --no-restore --nologo

      - name: Run DemoFeed
        run: |
          $ErrorActionPreference = 'Stop'
          $logPath = 'demo-ctrader.log'
          $args = @('--run-id', $env:RUN_ID, '--broker-enabled', 'true', '--broker-fill-mode', 'ioc-market')
          dotnet exec src/TiYf.Engine.DemoFeed/bin/Release/net8.0/TiYf.Engine.DemoFeed.dll @args | Tee-Object -FilePath $logPath
          $exitCode = $LASTEXITCODE
          if ($exitCode -ne 0) { throw "DemoFeed exited with $exitCode" }
          $eventsLine = Select-String -Path $logPath -Pattern '^JOURNAL_DIR_EVENTS='
          $tradesLine = Select-String -Path $logPath -Pattern '^JOURNAL_DIR_TRADES='
          $runDirLine = Select-String -Path $logPath -Pattern '^RUN_DIR='
          $infoLine = Select-String -Path $logPath -Pattern '^INFO first_ts='
          if (-not $eventsLine -or -not $tradesLine -or -not $runDirLine -or -not $infoLine) { throw "Missing output lines" }
          $eventsPath = ($eventsLine | Select-Object -First 1).Line.Split('=')[1]
          $tradesPath = ($tradesLine | Select-Object -First 1).Line.Split('=')[1]
          $runDirectory = ($runDirLine | Select-Object -First 1).Line.Split('=')[1]
          $brokerDangling = if ($infoLine -match 'broker_dangling=(true|false)') { $matches[1] } else { 'unknown' }
          "EVENTS_PATH=$eventsPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "TRADES_PATH=$tradesPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RUN_DIR=$runDirectory" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "BROKER_DANGLING=$brokerDangling" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Verify Strict
        run: |
          $ErrorActionPreference = 'Stop'
          dotnet exec src/TiYf.Engine.Tools/bin/Release/net8.0/TiYf.Engine.Tools.dll verify strict --events $env:EVENTS_PATH --trades $env:TRADES_PATH --schema 1.3.0 --json | Tee-Object -FilePath 'strict.json'
          $strictExit = $LASTEXITCODE
          "STRICT_EXIT=$strictExit" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Verify Parity
        run: |
          $ErrorActionPreference = 'Stop'
          dotnet exec src/TiYf.Engine.Tools/bin/Release/net8.0/TiYf.Engine.Tools.dll verify parity --events-a $env:EVENTS_PATH --events-b $env:EVENTS_PATH --trades-a $env:TRADES_PATH --trades-b $env:TRADES_PATH --json | Tee-Object -FilePath 'parity.json'
          $parityExit = $LASTEXITCODE
          "PARITY_EXIT=$parityExit" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Collect Artifacts
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -ItemType Directory -Path 'artifacts' -Force
          Copy-Item -Path $env:EVENTS_PATH -Destination 'artifacts/events.csv' -Force
          Copy-Item -Path $env:TRADES_PATH -Destination 'artifacts/trades.csv' -Force
          Copy-Item -Path 'strict.json' -Destination 'artifacts/strict.json' -Force
          Copy-Item -Path 'parity.json' -Destination 'artifacts/parity.json' -Force
          Copy-Item -Path 'demo-ctrader.log' -Destination 'artifacts/demo-ctrader.log' -Force
          Copy-Item -Path 'preflight.sanity.txt' -Destination 'artifacts/preflight.sanity.txt' -Force

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: demo-daily-ctrader-${{ env.RUN_ID }}
          path: artifacts/**

concurrency:
  group: demo-daily-ctrader
  cancel-in-progress: false

