name: M4 Risk Matrix

on:
  workflow_dispatch:
  push:
    branches:
      - feat/m4-risk-rails
  pull_request:
    branches:
      - feat/m4-risk-rails

jobs:
  risk-proof:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore and build (Release)
        run: |
          set -euo pipefail
          dotnet restore TiYf.Engine.sln
          dotnet build TiYf.Engine.sln -c Release --no-restore --nologo

      - name: Ensure jq
        run: |
          set -euo pipefail
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

      - name: Run session gate proof
        run: |
          set -euo pipefail
          bash scripts/ci/risk-rails-proof.sh proof/session.json artifacts/session

      - name: Run daily cap proof
        run: |
          set -euo pipefail
          bash scripts/ci/risk-rails-proof.sh proof/dailycap.json artifacts/dailycap

      - name: Run global drawdown proof
        run: |
          set -euo pipefail
          bash scripts/ci/risk-rails-proof.sh proof/drawdown.json artifacts/drawdown proof/drawdown-snapshot.json

      - name: Run news blackout proof
        run: |
          set -euo pipefail
          bash scripts/ci/risk-rails-proof.sh proof/news.json artifacts/news

      - name: Build summary
        run: |
          set -euo pipefail
          > artifacts/summary.txt
          for gate in session dailycap drawdown news; do
            alert=$(grep -m1 -E 'ALERT_(BLOCK|THROTTLE)_' artifacts/$gate/events.csv || true)
            if [[ -z "$alert" ]]; then
              echo "$gate: NOT FOUND" >> artifacts/summary.txt
            else
              echo "$gate: $alert" >> artifacts/summary.txt
            fi
          done
          cat artifacts/summary.txt

      - name: Upload proof artifacts
        uses: actions/upload-artifact@v4
        with:
          name: m4-risk-proof
          path: artifacts
