name: nightly-canary

on:
  schedule:
    - cron: '0 5 * * *' # daily at 05:00 UTC
  workflow_dispatch: {}
  push:
    branches: [ feat/m5-seed ]
  pull_request:
    branches: [ main, feat/m4-seed, feat/m5-seed ]

concurrency:
  group: nightly-canary
  cancel-in-progress: true

jobs:
  canary:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [ off, shadow, active, penalty-active ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Clean tree guard
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "$(git status --porcelain)" ]; then echo "Dirty tree before build"; git status; exit 1; fi
      - name: Build (Release)
        run: dotnet build TiYf.Engine.sln -c Release --nologo
      - name: Run simulation (mode=${{ matrix.mode }})
        env:
          MODE: ${{ matrix.mode }}
        shell: bash
        run: |
          set -euo pipefail
          ROOT="$GITHUB_WORKSPACE"
          SIM="$ROOT/src/TiYf.Engine.Sim/bin/Release/net8.0/TiYf.Engine.Sim.dll"
          BASE_CFG="$ROOT/tests/fixtures/backtest_m0/config.backtest-m0.json"
          OUTCFG=$(mktemp)
          # Ensure jq exists
          if ! command -v jq >/dev/null 2>&1; then sudo apt-get update && sudo apt-get install -y jq; fi
          # Base toggles: disable unrelated systems for isolation
          jq '.featureFlags.sentiment="off" | .featureFlags.risk="off"' "$BASE_CFG" > "$OUTCFG"
          # Apply penalty mode
          case "$MODE" in
            off)
              jq '.featureFlags.penalty="off"' "$OUTCFG" > "$OUTCFG.tmp" && mv "$OUTCFG.tmp" "$OUTCFG"
              ;;
            shadow)
              jq '.featureFlags.penalty="shadow"' "$OUTCFG" > "$OUTCFG.tmp" && mv "$OUTCFG.tmp" "$OUTCFG"
              ;;
            active)
              jq '.featureFlags.penalty="active"' "$OUTCFG" > "$OUTCFG.tmp" && mv "$OUTCFG.tmp" "$OUTCFG"
              ;;
            penalty-active)
              jq '.featureFlags.penalty="active" | .penaltyConfig = (.penaltyConfig // {}) | .penaltyConfig.forcePenalty=true | .ciPenaltyScaffold=true' "$OUTCFG" > "$OUTCFG.tmp" && mv "$OUTCFG.tmp" "$OUTCFG"
              ;;
          esac
          echo "Mutated config for mode=$MODE -> $OUTCFG"
          echo "OUTCFG=$OUTCFG" >> "$GITHUB_ENV"
          rm -rf "$ROOT/journals" || true
          RUN_ID=CANARY-$MODE-A
          OUT=$(mktemp)
          set +e
          dotnet exec "$SIM" --config "$OUTCFG" --quiet --run-id "$RUN_ID" | tee "$OUT"
          CODE=$?
          set -e
          if [ $CODE -ne 0 ]; then
            echo "Simulator exited with code $CODE" >&2
            exit $CODE
          fi
          EV=$(grep -m1 '^JOURNAL_DIR_EVENTS=' "$OUT" | cut -d= -f2 || true)
          TR=$(grep -m1 '^JOURNAL_DIR_TRADES=' "$OUT" | cut -d= -f2 || true)
          RUN_DIR=""
          if [ -n "$EV" ] && [ -n "$TR" ]; then
            RUN_DIR="$(dirname "$EV")"
          fi
          if [ -z "$EV" ] || [ -z "$TR" ]; then
            echo "Missing JOURNAL_DIR entries in simulator output" >&2
            echo '--- simulator stdout ---'
            cat "$OUT"
            exit 2
          fi
          test -f "$EV" && test -f "$TR"
          RUN_DIR=$(dirname "$EV")
          mkdir -p artifacts/parity/$MODE artifacts/parity/$MODE/env artifacts/parity/$MODE/journals
          {
            echo "RUN_DIR=$RUN_DIR"
            echo "EVENTS=$EV"
            echo "TRADES=$TR"
          } >> "$GITHUB_ENV"
          ENV_SANITY=artifacts/parity/$MODE/env.sanity
          {
            echo "mode=$MODE"
            echo "run_dir=$RUN_DIR"
            echo "events=$EV"
            echo "trades=$TR"
          } >> "$ENV_SANITY"
          cp "$OUT" artifacts/parity/$MODE/sim.log || true
          cp "$EV" artifacts/parity/$MODE/journals/events.csv
          cp "$TR" artifacts/parity/$MODE/journals/trades.csv
          # Normalize events: skip meta + header
          tail -n +3 "$EV" | sha256sum | awk '{print $1}' > artifacts/parity/$MODE/events.sha
          # Normalize trades: remove header + strip config_hash column if present
          awk -F, 'NR==1 {for (i=1;i<=NF;i++){if($i=="config_hash") c=i} next} {out=""; for(i=1;i<=NF;i++){ if(i==c) continue; if(out!="") out=out","; out=out $i;} print out}' "$TR" | sha256sum | awk '{print $1}' > artifacts/parity/$MODE/trades.sha
          EVENTS_SHA=$(cat artifacts/parity/$MODE/events.sha)
          TRADES_SHA=$(cat artifacts/parity/$MODE/trades.sha)
          PEN_CNT=$(grep -c ',PENALTY_APPLIED_V1,' "$EV" || true)
          {
            echo "mode=$MODE"
            echo "events_sha=$EVENTS_SHA"
            echo "trades_sha=$TRADES_SHA"
            echo "penalty_count=$PEN_CNT"
            echo "run_dir=$RUN_DIR"
            echo "events=$EV"
            echo "trades=$TR"
          } > artifacts/parity/$MODE/hashes.txt
          cp artifacts/parity/$MODE/hashes.txt artifacts/parity/$MODE/hashes-$MODE.txt || true
          echo "--- hashes ($MODE A) ---"; cat artifacts/parity/$MODE/hashes.txt

      - name: Back-to-back run B (mode=${{ matrix.mode }})
        env:
          MODE: ${{ matrix.mode }}
        shell: bash
        run: |
          set -euo pipefail
          ROOT="$GITHUB_WORKSPACE"
          SIM="$ROOT/src/TiYf.Engine.Sim/bin/Release/net8.0/TiYf.Engine.Sim.dll"
          BASE_CFG="$ROOT/tests/fixtures/backtest_m0/config.backtest-m0.json"
          OUTCFG_B=$(mktemp)
          cp "$OUTCFG" "$OUTCFG_B"
          RUN_ID=CANARY-$MODE-B
          OUT=$(mktemp)
          dotnet exec "$SIM" --config "$OUTCFG_B" --quiet --run-id "$RUN_ID" | tee "$OUT"
          RUN_DIR=$(ls -d "$ROOT"/journals/*"$RUN_ID"* 2>/dev/null | head -n1 || true)
          echo "RUN_DIR_B=$RUN_DIR"; test -n "$RUN_DIR"
          EV_B="$RUN_DIR/events.csv"; TR_B="$RUN_DIR/trades.csv"
          test -f "$EV_B"; test -f "$TR_B"
          echo "B events=$EV_B trades=$TR_B"

      - name: Verify parity (events + trades)
        shell: bash
        run: |
          set -euo pipefail
          ROOT="$GITHUB_WORKSPACE"
          TOOLS="$ROOT/src/TiYf.Engine.Tools/bin/Release/net8.0/TiYf.Engine.Tools.dll"
          A_DIR="$ROOT/journals/M0/CANARY-${{ matrix.mode }}-A"
          B_DIR="$ROOT/journals/M0/CANARY-${{ matrix.mode }}-B"
          mkdir -p artifacts/parity/${{ matrix.mode }}
          set +e
          dotnet exec "$TOOLS" verify parity \
            --events-a "$A_DIR/events.csv" --events-b "$B_DIR/events.csv" \
            --trades-a "$A_DIR/trades.csv" --trades-b "$B_DIR/trades.csv" --json | tee artifacts/parity/${{ matrix.mode }}/parity-parrot.json
          code=$?
          set -e
          echo "parity_exit_code=$code"
          exit $code

      - name: Parity job summary (per-mode)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          FILE="artifacts/parity/${{ matrix.mode }}/parity-parrot.json"
          echo "# Nightly parity (${{ matrix.mode }})" >> "$GITHUB_STEP_SUMMARY"
          if [ -f "$FILE" ]; then
            # Quick check: exitCode 0 in JSON
            ok=$(grep -c '"exitCode":0' "$FILE" || true)
            if [ "$ok" -gt 0 ]; then
              echo "✅ parity OK (mode=${{ matrix.mode }}) — events & trades match" >> "$GITHUB_STEP_SUMMARY"
            else
              echo "❌ parity drift (mode=${{ matrix.mode }}) — see artifacts for first-diff diagnostics" >> "$GITHUB_STEP_SUMMARY"
            fi
          else
            echo "⚠️ parity-parrot.json not found for mode ${{ matrix.mode }}" >> "$GITHUB_STEP_SUMMARY"
          fi
      - name: Upload parity artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parity-${{ matrix.mode }}
          path: artifacts/parity/${{ matrix.mode }}

  invariants:
    needs: canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download parity artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: parity-*
          path: parity_all
      - name: Evaluate invariants and publish summary
        shell: bash
        run: |
          set -euo pipefail
          echo 'Collected parity hash files:' >&2
          find parity_all -type f -name 'hashes*.txt' -print -exec cat {} \; || true
          declare -A TSHAS PS COUNT
          shopt -s nullglob globstar
          files=(parity_all/parity-*/hashes.txt)
          if [ ${#files[@]} -eq 0 ]; then
            files=(parity_all/**/hashes-*.txt)
          fi
          for f in "${files[@]}"; do
            base=$(basename "$f")
            dir=$(basename "$(dirname "$f")")
            mode=''
            if [[ "$base" =~ ^hashes-([a-z_-]+)\.txt$ ]]; then
              mode="${BASH_REMATCH[1]}"
            elif [[ "$dir" =~ ^parity-(.*)$ ]]; then
              mode="${BASH_REMATCH[1]}"
            else
              mode=$(grep -m1 '^mode=' "$f" | cut -d= -f2 || true)
            fi
            [ -n "$mode" ] || { echo "Could not determine mode for $f" >&2; continue; }
            tsha=$(grep -m1 '^trades_sha=' "$f" | cut -d= -f2)
            pcount=$(grep -m1 '^penalty_count=' "$f" | cut -d= -f2)
            TSHAS[$mode]="$tsha"
            COUNT[$mode]="$pcount"
          done
          # Required modes presence
          for m in off shadow active penalty-active; do
            [ -n "${TSHAS[$m]:-}" ] || { echo "Missing mode $m" >&2; exit 1; }
          done
          # Invariants: off vs shadow equal; shadow vs active equal
          [ "${TSHAS[off]}" = "${TSHAS[shadow]}" ] || { echo 'off vs shadow trades hash mismatch' >&2; exit 1; }
          [ "${TSHAS[shadow]}" = "${TSHAS[active]}" ] || { echo 'shadow vs active trades hash mismatch' >&2; exit 1; }
          # penalty-active must have at least one penalty event (forced)
          if [ "${COUNT[penalty-active]}" -lt 1 ]; then echo 'penalty-active produced no penalty events' >&2; exit 1; fi
          # Write a human-readable summary
          mkdir -p artifacts
          {
            echo "mode,trades_sha,penalty_count"
            for m in off shadow active penalty-active; do
              echo "$m,${TSHAS[$m]},${COUNT[$m]}"
            done
          } > artifacts/parity_summary.csv
          echo 'Nightly canary invariants satisfied.'
      - name: Job summary (parity table)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          echo "# Nightly Canary Parity Summary" >> "$GITHUB_STEP_SUMMARY"
          if [ -f artifacts/parity_summary.csv ]; then
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "mode,trades_sha,penalty_count" >> "$GITHUB_STEP_SUMMARY"
            tail -n +2 artifacts/parity_summary.csv >> "$GITHUB_STEP_SUMMARY"
          else
            echo "(parity_summary.csv not found)" >> "$GITHUB_STEP_SUMMARY"
          fi
      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: nightly-canary-summary
          path: artifacts/parity_summary.csv
