name: push-test

on:
  push:
    branches: [ feat/m4-risk-rails ]

jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore & build
        run: |
          set -euo pipefail
          dotnet restore TiYf.Engine.sln
          dotnet build TiYf.Engine.sln -c Release --no-restore --nologo
      - name: Run risk rails proof script
        run: |
          set -euo pipefail
          bash scripts/ci/risk-rails-proof.sh
      - name: Show summary
        run: |
          cat proof/proof-summary.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: risk-rails-proof
          path: proof
